services:
  bid-buddy-db:
    image: postgres
    restart: always
    container_name: bid-buddy-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
